import { test, expect } from '@fixtures/base-test';

import { OwnerPage } from '@pages/owner-page';
import { createPet } from '@utils/pet-factory';

const formatFutureDate = (daysAhead: number) => {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);

  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');

  return `${year}-${month}-${day}`;
};

test.describe('Pet Management', () => {
  test('can add a pet to an existing owner and see it on owner details', async ({ page }, testInfo) => {
    const ownerPage = new OwnerPage(page);
    const pet = createPet({ type: 'cat' });

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    await page.getByRole('link', { name: /Add New Pet/i }).click();

    // Form fields are generated by thymeleaf fragments: ids match field names
    await page.locator('input#name').fill(pet.name);
    await page.locator('input#birthDate').fill(pet.birthDate);
    await page.locator('select#type').selectOption({ label: pet.type });

    await page.screenshot({ path: testInfo.outputPath('pet-add-form-filled.png'), fullPage: true });

    await page.getByRole('button', { name: /Add Pet/i }).click();

    // Back on owner details
    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(page.getByText(pet.name, { exact: true })).toBeVisible();

    // Add a visit for the newly-created pet and verify it shows under visit history.
    const petRow = page.locator('tr').filter({
      has: page.locator('dd', { hasText: pet.name })
    });

    await petRow.getByRole('link', { name: /Add Visit/i }).first().click();

    const visitDate = formatFutureDate(7);

    await page.locator('input#date').fill(visitDate);
    await page.locator('input#description').fill('Annual checkup');
    await page.screenshot({ path: testInfo.outputPath('visit-add-form-filled.png'), fullPage: true });
    await page.getByRole('button', { name: /Add Visit/i }).click();

    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(petRow.getByRole('cell', { name: visitDate, exact: true })).toBeVisible();
    await expect(petRow.getByRole('cell', { name: 'Annual checkup', exact: true })).toBeVisible();

    await page.screenshot({ path: testInfo.outputPath('pet-details-with-visit-history.png'), fullPage: true });
  });

  test('validates pet type selection and birth date format', async ({ page }) => {
    const ownerPage = new OwnerPage(page);

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    await page.getByRole('link', { name: /Add New Pet/i }).click();

    // Validate required fields (observable via UI): leave name and birth date empty.
    await page.locator('select#type').selectOption({ index: 0 });
    await page.getByRole('button', { name: /Add Pet/i }).click();

    await expect(page.getByText(/is required/i)).toHaveCount(2);
  });

  test('can delete a pet with no visits', async ({ page }, testInfo) => {
    const ownerPage = new OwnerPage(page);
    const pet = createPet({ type: 'cat' });

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    // Create pet
    await page.getByRole('link', { name: /Add New Pet/i }).click();
    await page.locator('input#name').fill(pet.name);
    await page.locator('input#birthDate').fill(pet.birthDate);
    await page.locator('select#type').selectOption({ label: pet.type });
    await page.getByRole('button', { name: /Add Pet/i }).click();
    await expect(page.getByText(pet.name, { exact: true })).toBeVisible();

    // Delete pet — find the trigger in the pet's row
    const petRow = page.locator('tr').filter({
      has: page.locator('dd', { hasText: pet.name }),
    });
    await petRow.getByRole('link', { name: /Delete/i }).click();

    // Modal should be visible with "Delete" button (not "Delete anyway")
    await expect(page.locator('#deletePetModal')).toBeVisible();
    await expect(page.locator('#confirmDeleteBtn')).toHaveText('Delete');
    await page.screenshot({
      path: testInfo.outputPath('delete-modal-no-visit.png'),
    });

    // Confirm deletion
    await page.locator('#confirmDeleteBtn').click();

    // Pet must no longer appear
    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(page.getByText(pet.name, { exact: true })).not.toBeVisible();
  });

  test('can delete a pet with visits and sees visit-count warning', async ({ page }, testInfo) => {
    const ownerPage = new OwnerPage(page);
    const pet = createPet({ type: 'dog' });

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    // Create pet
    await page.getByRole('link', { name: /Add New Pet/i }).click();
    await page.locator('input#name').fill(pet.name);
    await page.locator('input#birthDate').fill(pet.birthDate);
    await page.locator('select#type').selectOption({ label: pet.type });
    await page.getByRole('button', { name: /Add Pet/i }).click();
    await expect(page.getByText(pet.name, { exact: true })).toBeVisible();

    // Add a visit
    const petRow = page.locator('tr').filter({
      has: page.locator('dd', { hasText: pet.name }),
    });
    await petRow.getByRole('link', { name: /Add Visit/i }).first().click();
    await page.locator('input#date').fill(formatFutureDate(30));
    await page.locator('input#description').fill('Wellness check');
    await page.getByRole('button', { name: /Add Visit/i }).click();
    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();

    // Delete pet — modal should show visit-count warning
    const petRowAfterVisit = page.locator('tr').filter({
      has: page.locator('dd', { hasText: pet.name }),
    });
    await petRowAfterVisit.getByRole('link', { name: /Delete/i }).click();

    await expect(page.locator('#deletePetModal')).toBeVisible();
    await expect(page.locator('#modalVisitWarning')).toBeVisible();
    await expect(page.locator('#confirmDeleteBtn')).toHaveText('Delete anyway');
    await page.screenshot({
      path: testInfo.outputPath('delete-modal-with-visit-warning.png'),
    });

    // Confirm deletion
    await page.locator('#confirmDeleteBtn').click();

    // Pet must no longer appear
    await expect(page.getByText(pet.name, { exact: true })).not.toBeVisible();
  });
});
