services:
  floci:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 0
      ECS_REMOVE_CONTAINERS: 1
      SERVICES: s3,dynamodb,sts,ec2,ecr,ecs,elbv2,iam,logs
